# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 18:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0008_courses_small_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(max_length=40),
        ),
    ]
