# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0009_auto_20161111_1847'),
    ]

    operations = [
        migrations.AddField(
            model_name='courses',
            name='code_url',
            field=models.URLField(default='null'),
            preserve_default=False,
        ),
    ]
