# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0010_courses_code_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
                ('num_pos', models.IntegerField()),
                ('posted_on', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to=b'photos/%Y/%m/%d')),
            ],
        ),
    ]
