# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-11 20:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0011_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='companies',
            field=models.TextField(default='MindLogix - www.mindlogicx.com'),
            preserve_default=False,
        ),
    ]
