# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-11-12 06:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prof', '0012_jobs_companies'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='slug',
            field=models.CharField(default='dummy', max_length=100),
            preserve_default=False,
        ),
    ]
